//HomeScreen
const SET_CHARACTER = 'SET_CHARACTER';
const RESET = 'reset';
const ADD_STAT = 'ADD_STAT';
const ADD_SKILL = 'ADD_SKILL';
const REMOVE_SKILL = 'REMOVE_SKILL';
const RANK_SKILL = 'RANK_SKILL';
const SET_MODAL_SKILL = 'SET_MODAL_SKILL';
const SET_SELECTED_MODAL_SKILL = 'SET_SELECTED_MODAL_SKILL';
const SET_CHARACTER_SKILL = 'SET_CHARACTER_SKILL';

//SettingsScreen
const SET_CREATE_ACCOUNT_MODAL = 'SET_CREATE_ACCOUNT_MODAL';
const SET_ACCOUNT_EMAIL = 'SET_ACCOUNT_EMAIL';
const SET_ACCOUNT_PASSWORD = 'SET_ACCOUNT_PASSWORD';
const SET_CURRENT_BUILD_NAME = 'SET_CURRENT_BUILD_NAME';
const SET_SAVE_BUILD_MODAL = 'SET_SAVE_BUILD_MODAL';
const SAVE_BUILD = 'SAVE_BUILD';
const SET_HERO_SELECT = 'SET_HERO_SELECT';
const SELECT_HERO = 'SELECT_HERO';
const TOGGLE = 'TOGGLE'
const TOGGLE_QUICK_SELECT = 'TOGGLE_QUICK_SELECT';
const TOGGLE_ACTIONS = 'TOGGLE_ACTIONS';
const TOGGLE_BUILDS = 'TOGGLE_BUILDS';

export { 
    SET_CHARACTER, 
    RESET,
    ADD_SKILL, 
    REMOVE_SKILL, 
    RANK_SKILL, 
    ADD_STAT, 
    SET_MODAL_SKILL, 
    SET_SELECTED_MODAL_SKILL,
    SET_CHARACTER_SKILL,

    SET_CREATE_ACCOUNT_MODAL,
    SET_ACCOUNT_EMAIL,
    SET_ACCOUNT_PASSWORD,
    SET_CURRENT_BUILD_NAME,
    SET_SAVE_BUILD_MODAL,
    SAVE_BUILD,
    SET_HERO_SELECT,
    SELECT_HERO,
    TOGGLE,
    TOGGLE_QUICK_SELECT,
    TOGGLE_ACTIONS,
    TOGGLE_BUILDS
};